# Site/SEO settings
email: ilona.stuetz@ufg.at
baseurl: "/kulturbeutel"
permalink: /:year/:month/:day/:title/

name: Ilona Stuetz
title: Kulturbeutel-Sammlung gelesener Bücher und gesehener Theaterstücke
description: >
  Sammlung gelesener Bücher und gesehener Theaterstücke
url: https://il0n4.github.io/kulturbeutel
twitter_username: ilo_ul
default_img: /assets/images/seo.jpg
social:
  - name: twitter
    url: https://twitter.com/ilo_ul
  - name: github
    url: https://github.com/il0n4
  - name: codepen
    url: illustworkspace.wordpress.com

# Contact settings
#contact_img: /assets/images/placeholder-28.jpg
#formcarry: https://formcarry.com/s/HkIo0nMb7

# Disqus settings
#disqus: test-apkdzgmqhj


# Author settings
author:
  - name: Ilona Stuetz
    bio: Ilona Stuetz lebt in Berlin. Hier arbeitet sie als Medienpädagogin unter anderem für Jugend hackt. Sie interessiert sich für Technik und Design. Vor allem aber, wie und ob sich Technik und Design an den Anwender*innen orientiert. Ausserdem geht sie sehr häufig ins Theater.
    url: https://il0n4.github.io/kulturbeutel/
    
# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 12
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts: 
      - 'tag.html'
    title: 'The Barber Theme'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
